"""
Question banks for the OS / DBMS / DSA courses.

This content previously existed ONLY as unused mock data inside
frontend/src/api.js (mockQuestions) -- the frontend selector (course + mode)
had nothing real to talk to on the backend, so every course/mode combination
silently fell back to the generic arithmetic bank in questions.json. Moving
it here makes it the actual content the backend serves.

Each course now has real coverage across all three tiers (2 MCQ + spread of
short-answer per tier) so the "pick a random question, excluding the one you
just answered" logic in main.py always has more than one option to draw
from -- with only 1 question in a pool, "Next Question" has no choice but to
show you the same question again, which is what was happening before.

Every short-answer question also carries a "model_answer" -- a full
reference sentence, not just a bag of keywords -- so keyword_grader.py can
hand it to the local LLM (or the natural-language fallback) to explain what
the player got right or missed in plain English instead of a label dump.
"""

OS_QUESTIONS = [
    {
        "id": "os-mcq-1",
        "courseId": "os",
        "mode": "mcq",
        "tier": 1,
        "prompt": "Which CPU scheduling algorithm gives minimum average waiting time for a given set of processes?",
        "options": ["FCFS", "SJF", "Round Robin", "Priority Scheduling"],
        "correct_answer": "SJF",
        "explanation": "Shortest Job First (SJF) always runs whichever ready process needs the least CPU time next, so short jobs never sit queued behind long ones -- that's what minimizes average waiting time.",
    },
    {
        "id": "os-mcq-3",
        "courseId": "os",
        "mode": "mcq",
        "tier": 1,
        "prompt": "What is a process, in operating systems terms?",
        "options": ["A program in execution", "A file saved on disk", "A physical hardware device", "A network data packet"],
        "correct_answer": "A program in execution",
        "explanation": "A program is just static code sitting on disk. The moment the OS loads it, gives it memory, and starts running its instructions, it becomes a process -- a live, running instance with its own state.",
    },
    {
        "id": "os-mcq-2",
        "courseId": "os",
        "mode": "mcq",
        "tier": 2,
        "prompt": "What condition occurs when processes spend significantly more time paging than executing instructions?",
        "options": ["Starvation", "Deadlock", "Thrashing", "Internal Fragmentation"],
        "correct_answer": "Thrashing",
        "explanation": "Thrashing happens when too many processes compete for too little physical memory, so the OS spends most of its time swapping pages in and out instead of running processes -- CPU utilization actually drops even though the system looks busy.",
    },
    {
        "id": "os-mcq-4",
        "courseId": "os",
        "mode": "mcq",
        "tier": 2,
        "prompt": "Which page replacement algorithm can suffer from Belady's Anomaly, where adding more frames actually increases the number of page faults?",
        "options": ["FIFO", "LRU", "Optimal", "LFU"],
        "correct_answer": "FIFO",
        "explanation": "FIFO replaces the oldest-loaded page regardless of how recently it was used, which can occasionally make more memory frames perform worse. LRU and Optimal don't have this quirk because they factor in actual usage.",
    },
    {
        "id": "os-mcq-5",
        "courseId": "os",
        "mode": "mcq",
        "tier": 3,
        "prompt": "In the Banker's Algorithm, what is checked before a resource request is granted?",
        "options": [
            "Whether granting it would leave the system in a safe state",
            "Whether the requesting process has the highest priority",
            "Whether the CPU is currently idle",
            "Whether the disk has enough free space",
        ],
        "correct_answer": "Whether granting it would leave the system in a safe state",
        "explanation": "The Banker's Algorithm simulates granting the request and checks whether there's still some order in which every process could finish. If that safe sequence exists, it grants the request; otherwise, it makes the process wait to avoid a deadlock.",
    },
    {
        "id": "os-mcq-6",
        "courseId": "os",
        "mode": "mcq",
        "tier": 3,
        "prompt": "What distinguishes a deadlock from starvation?",
        "options": [
            "Deadlock is a circular wait where no process can ever progress; starvation is indefinite postponement while other processes keep progressing",
            "They describe exactly the same situation",
            "Deadlock can only happen with a single process",
            "Starvation requires at least four processes",
        ],
        "correct_answer": "Deadlock is a circular wait where no process can ever progress; starvation is indefinite postponement while other processes keep progressing",
        "explanation": "In a deadlock, the involved processes are permanently stuck waiting on each other. In starvation, the system as a whole keeps making progress -- it's just that one unlucky process (often low priority) keeps getting skipped over.",
    },
]

OS_SHORT_ANSWER = [
    {
        "id": "os-sa-2",
        "courseId": "os",
        "mode": "short_answer",
        "tier": 1,
        "prompt": "What is the difference between a process and a thread?",
        "model_answer": "A process is an independent program in execution with its own separate memory space, while a thread is a lightweight unit of execution inside a process that shares that process's memory with its other threads, making threads faster to create and switch between.",
        "min_clusters_required": 2,
        "keyword_clusters": [
            {"name": "Own Memory Space", "aliases": ["own memory", "separate memory", "independent memory space", "own address space"]},
            {"name": "Shared Memory Between Threads", "aliases": ["shares memory", "shared memory", "same memory space", "share the same memory"]},
            {"name": "Lightweight / Faster", "aliases": ["lightweight", "faster context switch", "less overhead", "cheaper to create"]},
        ],
    },
    {
        "id": "os-sa-1",
        "courseId": "os",
        "mode": "short_answer",
        "tier": 2,
        "prompt": "Explain how Thrashing occurs in Virtual Memory.",
        "model_answer": "Thrashing happens when there are too many processes competing for too little physical RAM, so the system spends almost all its time swapping pages in and out of disk (constant page faults) instead of running processes, which causes CPU utilization to actually drop.",
        "min_clusters_required": 2,
        "keyword_clusters": [
            {"name": "Page Faults", "aliases": ["page fault", "page faults", "paging", "high page faults"]},
            {"name": "Swapping", "aliases": ["swapping", "swap", "disk i/o", "pages in and out"]},
            {"name": "CPU Drop", "aliases": ["cpu utilization drops", "low cpu", "cpu idle", "cpu underutilization"]},
        ],
    },
    {
        "id": "os-sa-3",
        "courseId": "os",
        "mode": "short_answer",
        "tier": 2,
        "prompt": "What causes a Deadlock, and name one of the conditions required for it?",
        "model_answer": "A deadlock occurs when a group of processes are each waiting for a resource held by another process in that same group, so none of them can ever proceed. Four conditions must all hold for it to happen: mutual exclusion, hold and wait, no preemption, and circular wait.",
        "min_clusters_required": 2,
        "keyword_clusters": [
            {"name": "Circular Wait", "aliases": ["circular wait", "waiting in a circle", "cycle of processes", "each waiting on the next"]},
            {"name": "Mutual Exclusion", "aliases": ["mutual exclusion", "exclusive access", "one process at a time"]},
            {"name": "Hold and Wait", "aliases": ["hold and wait", "holding a resource while waiting", "holding resources"]},
        ],
    },
    {
        "id": "os-sa-4",
        "courseId": "os",
        "mode": "short_answer",
        "tier": 3,
        "prompt": "Explain the difference between preemptive and non-preemptive scheduling.",
        "model_answer": "In preemptive scheduling, the OS can forcibly take the CPU away from a running process to give it to another, higher-priority one (like Round Robin). In non-preemptive scheduling, once a process gets the CPU it keeps it until it finishes or voluntarily gives it up (like FCFS).",
        "min_clusters_required": 2,
        "keyword_clusters": [
            {"name": "CPU Can Be Taken Away", "aliases": ["taken away", "interrupted", "forcibly removed", "preempted", "can be preempted"]},
            {"name": "Runs Until Done", "aliases": ["runs until it finishes", "voluntarily", "until completion", "yields the cpu"]},
            {"name": "Examples", "aliases": ["round robin", "fcfs", "priority scheduling", "sjf"]},
        ],
    },
    {
        "id": "os-sa-5",
        "courseId": "os",
        "mode": "short_answer",
        "tier": 1,
        "prompt": "What is the difference between Paging and Segmentation?",
        "model_answer": "Paging splits memory into fixed-size blocks called pages/frames, so allocation is simple but doesn't reflect the program's logical structure. Segmentation splits memory into variable-sized segments that map to logical units like functions or data, which is more intuitive but harder to manage.",
        "min_clusters_required": 2,
        "keyword_clusters": [
            {"name": "Paging is Fixed-Size", "aliases": ["fixed size", "fixed-size", "equal size blocks", "same size pages"]},
            {"name": "Segmentation is Variable-Size", "aliases": ["variable size", "variable-size", "different sizes", "varying size"]},
            {"name": "Logical Units", "aliases": ["logical unit", "logical division", "functions or modules", "matches program structure"]},
        ],
    },
    {
        "id": "os-sa-6",
        "courseId": "os",
        "mode": "short_answer",
        "tier": 3,
        "prompt": "Explain the Producer-Consumer problem and how synchronization solves it.",
        "model_answer": "The Producer-Consumer problem happens when a producer adds items to a shared buffer and a consumer removes them, and without coordination the producer can overflow a full buffer or the consumer can read from an empty one. Synchronization tools like semaphores or mutexes fix this by making each side wait for the right condition (buffer not full / not empty) before proceeding.",
        "min_clusters_required": 2,
        "keyword_clusters": [
            {"name": "Shared Buffer", "aliases": ["shared buffer", "shared queue", "bounded buffer", "shared resource"]},
            {"name": "Race Condition Without Sync", "aliases": ["race condition", "buffer overflow", "read from empty", "without synchronization"]},
            {"name": "Semaphores/Mutex Solution", "aliases": ["semaphore", "mutex", "lock", "wait and signal"]},
        ],
    },
]

DBMS_QUESTIONS = [
    {
        "id": "dbms-mcq-1",
        "courseId": "dbms",
        "mode": "mcq",
        "tier": 1,
        "prompt": "Which ACID property guarantees that all operations in a transaction complete or none do?",
        "options": ["Atomicity", "Consistency", "Isolation", "Durability"],
        "correct_answer": "Atomicity",
        "explanation": "Atomicity treats a transaction as a single indivisible unit: either every operation in it commits, or the whole transaction is rolled back -- the database never ends up partially updated.",
    },
    {
        "id": "dbms-mcq-2",
        "courseId": "dbms",
        "mode": "mcq",
        "tier": 1,
        "prompt": "Which of these is a Data Definition Language (DDL) command?",
        "options": ["CREATE", "SELECT", "INSERT", "UPDATE"],
        "correct_answer": "CREATE",
        "explanation": "DDL commands (CREATE, ALTER, DROP) define or change the database's structure/schema. SELECT, INSERT, and UPDATE are DML commands -- they work with the data inside that structure, not the structure itself.",
    },
    {
        "id": "dbms-mcq-3",
        "courseId": "dbms",
        "mode": "mcq",
        "tier": 2,
        "prompt": "Which normal form eliminates transitive dependency on the primary key?",
        "options": ["1NF", "2NF", "3NF", "BCNF"],
        "correct_answer": "3NF",
        "explanation": "3NF requires that every non-key attribute depend only on the primary key directly -- not on another non-key attribute. Removing those transitive dependencies is exactly what separates 3NF from 2NF.",
    },
    {
        "id": "dbms-mcq-4",
        "courseId": "dbms",
        "mode": "mcq",
        "tier": 2,
        "prompt": "Which type of JOIN returns all rows from both tables, matching where possible and filling in NULLs elsewhere?",
        "options": ["INNER JOIN", "LEFT JOIN", "FULL OUTER JOIN", "CROSS JOIN"],
        "correct_answer": "FULL OUTER JOIN",
        "explanation": "A FULL OUTER JOIN keeps every row from both tables. Where a match exists the columns line up; where it doesn't, the missing side is padded with NULLs instead of dropping the row like an INNER JOIN would.",
    },
    {
        "id": "dbms-mcq-5",
        "courseId": "dbms",
        "mode": "mcq",
        "tier": 3,
        "prompt": "Which transaction isolation level prevents dirty reads, non-repeatable reads, AND phantom reads?",
        "options": ["Read Uncommitted", "Read Committed", "Repeatable Read", "Serializable"],
        "correct_answer": "Serializable",
        "explanation": "Serializable is the strictest isolation level -- transactions behave as if they ran one after another with no overlap at all, which is the only level that rules out all three anomalies, including phantom reads.",
    },
    {
        "id": "dbms-mcq-6",
        "courseId": "dbms",
        "mode": "mcq",
        "tier": 3,
        "prompt": "What is the primary purpose of indexing in a database?",
        "options": [
            "Speed up data retrieval, at the cost of extra storage and slightly slower writes",
            "Encrypt data at rest",
            "Enforce foreign key constraints",
            "Reduce the size of the database file",
        ],
        "correct_answer": "Speed up data retrieval, at the cost of extra storage and slightly slower writes",
        "explanation": "An index is essentially a sorted lookup structure built alongside the table, so the database can find matching rows without scanning every row. That speed comes at a cost: extra disk space, and every write now also has to update the index.",
    },
]

DBMS_SHORT_ANSWER = [
    {
        "id": "dbms-sa-2",
        "courseId": "dbms",
        "mode": "short_answer",
        "tier": 1,
        "prompt": "What is a Primary Key, and what property must it have?",
        "model_answer": "A primary key is a column (or combination of columns) that uniquely identifies each row in a table, and it must hold a unique, non-null value for every single row.",
        "min_clusters_required": 2,
        "keyword_clusters": [
            {"name": "Uniquely Identifies Rows", "aliases": ["uniquely identif", "unique identifier", "identifies each row", "identify a row"]},
            {"name": "Cannot Be Null", "aliases": ["not null", "cannot be null", "no null values", "can't be empty"]},
            {"name": "Must Be Unique", "aliases": ["unique", "no duplicates", "must be unique", "no two rows the same"]},
        ],
    },
    {
        "id": "dbms-sa-1",
        "courseId": "dbms",
        "mode": "short_answer",
        "tier": 2,
        "prompt": "Define a Foreign Key and its primary purpose.",
        "model_answer": "A foreign key is a column (or set of columns) in one table that references the primary key of another table, and its job is to enforce referential integrity -- guaranteeing the row it points to actually exists.",
        "min_clusters_required": 2,
        "keyword_clusters": [
            {"name": "Referential Integrity", "aliases": ["referential integrity", "integrity constraint"]},
            {"name": "Primary Key Link", "aliases": ["primary key", "references primary", "parent key"]},
            {"name": "Table Relationship", "aliases": ["relationship between tables", "connects tables", "child table"]},
        ],
    },
    {
        "id": "dbms-sa-3",
        "courseId": "dbms",
        "mode": "short_answer",
        "tier": 2,
        "prompt": "Explain what Normalization is and why it's used.",
        "model_answer": "Normalization is the process of organizing a database's tables to reduce redundant data and prevent update, insert, and delete anomalies -- usually by splitting data across related tables that follow rules like 1NF, 2NF, and 3NF.",
        "min_clusters_required": 2,
        "keyword_clusters": [
            {"name": "Reduce Redundancy", "aliases": ["redundan", "duplicate data", "repeated data", "avoid duplication"]},
            {"name": "Avoid Anomalies", "aliases": ["anomal", "update anomaly", "insert anomaly", "delete anomaly"]},
            {"name": "Normal Forms", "aliases": ["normal form", "1nf", "2nf", "3nf"]},
        ],
    },
    {
        "id": "dbms-sa-4",
        "courseId": "dbms",
        "mode": "short_answer",
        "tier": 3,
        "prompt": "What is a Deadlock in the context of database transactions, and how does it happen?",
        "model_answer": "A database deadlock happens when two or more transactions each hold a lock that the other one needs and end up waiting on each other, so neither can proceed -- the DBMS eventually resolves it by rolling back or aborting one of them.",
        "min_clusters_required": 2,
        "keyword_clusters": [
            {"name": "Circular Waiting", "aliases": ["circular wait", "waiting on each other", "each other's locks", "waiting for each other"]},
            {"name": "Locks Held", "aliases": ["lock", "holding a lock", "row lock", "table lock"]},
            {"name": "Rollback / Abort Resolution", "aliases": ["rollback", "abort", "kill one of the transactions", "one is aborted"]},
        ],
    },
    {
        "id": "dbms-sa-5",
        "courseId": "dbms",
        "mode": "short_answer",
        "tier": 1,
        "prompt": "What is a Composite Key?",
        "model_answer": "A composite key is a primary key made up of two or more columns combined, used when no single column is enough to uniquely identify a row, but the combination of those columns together is unique.",
        "min_clusters_required": 2,
        "keyword_clusters": [
            {"name": "Two or More Columns", "aliases": ["two or more columns", "multiple columns", "combination of columns", "more than one column"]},
            {"name": "Combined Uniqueness", "aliases": ["combination is unique", "together are unique", "jointly unique"]},
            {"name": "No Single Column Enough", "aliases": ["single column isn't enough", "one column alone", "no single column"]},
        ],
    },
    {
        "id": "dbms-sa-6",
        "courseId": "dbms",
        "mode": "short_answer",
        "tier": 3,
        "prompt": "Explain the difference between Optimistic and Pessimistic locking.",
        "model_answer": "Pessimistic locking grabs a lock on a row before reading or updating it, assuming conflicts will happen, which blocks other transactions until it's released. Optimistic locking assumes conflicts are rare, so it lets transactions proceed without locking and only checks for conflicts (e.g. via a version number) right before committing.",
        "min_clusters_required": 2,
        "keyword_clusters": [
            {"name": "Pessimistic Locks Upfront", "aliases": ["locks before", "locks upfront", "acquires a lock first", "blocks other transactions"]},
            {"name": "Optimistic Assumes No Conflict", "aliases": ["assumes no conflict", "assumes conflicts are rare", "no locking upfront"]},
            {"name": "Checked at Commit / Versioning", "aliases": ["version number", "checked at commit time", "checks before committing", "conflict check"]},
        ],
    },
]

DSA_QUESTIONS = [
    {
        "id": "dsa-mcq-1",
        "courseId": "dsa",
        "mode": "mcq",
        "tier": 1,
        "prompt": "What is the worst-case runtime complexity of standard QuickSort?",
        "options": ["O(n log n)", "O(n)", "O(n²)", "O(log n)"],
        "correct_answer": "O(n²)",
        "explanation": "QuickSort's worst case happens when the chosen pivot is repeatedly the smallest or largest element (e.g. an already-sorted array with a naive pivot pick), producing maximally unbalanced partitions and O(n²) time instead of the typical O(n log n).",
    },
    {
        "id": "dsa-mcq-2",
        "courseId": "dsa",
        "mode": "mcq",
        "tier": 1,
        "prompt": "What is the time complexity of searching for a value in a balanced Binary Search Tree?",
        "options": ["O(1)", "O(log n)", "O(n)", "O(n log n)"],
        "correct_answer": "O(log n)",
        "explanation": "Because a balanced BST's height is roughly log(n), each comparison eliminates about half of the remaining nodes -- the same idea as binary search on a sorted array.",
    },
    {
        "id": "dsa-mcq-3",
        "courseId": "dsa",
        "mode": "mcq",
        "tier": 2,
        "prompt": "Which data structure follows LIFO (Last In, First Out) ordering?",
        "options": ["Queue", "Stack", "Linked List", "Heap"],
        "correct_answer": "Stack",
        "explanation": "A stack only lets you add or remove from one end (the top), so whatever went in most recently is always the first thing to come back out -- that's LIFO.",
    },
    {
        "id": "dsa-mcq-4",
        "courseId": "dsa",
        "mode": "mcq",
        "tier": 2,
        "prompt": "What is the average-case time complexity of a lookup in a Hash Table?",
        "options": ["O(1)", "O(log n)", "O(n)", "O(n²)"],
        "correct_answer": "O(1)",
        "explanation": "With a good hash function and load factor, keys spread evenly across buckets, so on average a lookup just computes the hash and checks a near-empty bucket -- constant time. It degrades toward O(n) only if many keys collide into the same bucket.",
    },
    {
        "id": "dsa-mcq-5",
        "courseId": "dsa",
        "mode": "mcq",
        "tier": 3,
        "prompt": "Which traversal of a Binary Search Tree visits its nodes in sorted order?",
        "options": ["Pre-order", "In-order", "Post-order", "Level-order"],
        "correct_answer": "In-order",
        "explanation": "In-order traversal visits left subtree, then the node itself, then right subtree. In a BST that ordering always produces values from smallest to largest.",
    },
    {
        "id": "dsa-mcq-6",
        "courseId": "dsa",
        "mode": "mcq",
        "tier": 3,
        "prompt": "What is the time complexity of building a Min-Heap from an unsorted array of n elements?",
        "options": ["O(n log n)", "O(n)", "O(n²)", "O(log n)"],
        "correct_answer": "O(n)",
        "explanation": "It looks like it should be O(n log n) since each sift-down costs O(log n), but most nodes are near the bottom of the heap where sift-down barely does any work -- summed across all levels, the total comes out to O(n), not O(n log n).",
    },
]

DSA_SHORT_ANSWER = [
    {
        "id": "dsa-sa-2",
        "courseId": "dsa",
        "mode": "short_answer",
        "tier": 1,
        "prompt": "What is Big-O notation used for?",
        "model_answer": "Big-O notation describes the upper bound on how an algorithm's runtime or memory usage grows as the input size increases, which lets you compare algorithms' efficiency independent of hardware or any one specific input.",
        "min_clusters_required": 2,
        "keyword_clusters": [
            {"name": "Describes Growth Rate", "aliases": ["grows", "growth rate", "scales with input", "as input size increases", "as n grows"]},
            {"name": "Worst Case / Upper Bound", "aliases": ["worst case", "upper bound", "upper limit"]},
            {"name": "Compare Algorithms", "aliases": ["compare algorithms", "efficiency", "compare efficiency", "how fast an algorithm is"]},
        ],
    },
    {
        "id": "dsa-sa-1",
        "courseId": "dsa",
        "mode": "short_answer",
        "tier": 2,
        "prompt": "Describe how Separate Chaining handles collisions in a Hash Table.",
        "model_answer": "Separate chaining stores a linked list (or similar structure) at every bucket/slot of the hash table, so when two keys hash to the same index, both entries are simply appended to that bucket's list instead of overwriting each other.",
        "min_clusters_required": 2,
        "keyword_clusters": [
            {"name": "Linked List", "aliases": ["linked list", "chain", "linked lists"]},
            {"name": "Bucket/Slot", "aliases": ["bucket", "slot", "index array"]},
            {"name": "Collision Handling", "aliases": ["collision", "same hash", "overflow"]},
        ],
    },
    {
        "id": "dsa-sa-3",
        "courseId": "dsa",
        "mode": "short_answer",
        "tier": 2,
        "prompt": "Explain how Binary Search works and what precondition it requires.",
        "model_answer": "Binary search repeatedly checks the middle element of the array and eliminates half of the remaining search space depending on whether the target is smaller or larger than that middle element -- this only works if the array is sorted beforehand.",
        "min_clusters_required": 2,
        "keyword_clusters": [
            {"name": "Requires Sorted Input", "aliases": ["sorted", "must be sorted", "array is sorted", "needs to be sorted"]},
            {"name": "Checks the Middle Element", "aliases": ["middle element", "midpoint", "divide the array", "middle of the array"]},
            {"name": "Eliminates Half the Search Space", "aliases": ["eliminate half", "discard half", "narrows down", "reduces search space", "cuts the search space"]},
        ],
    },
    {
        "id": "dsa-sa-4",
        "courseId": "dsa",
        "mode": "short_answer",
        "tier": 3,
        "prompt": "What is Dynamic Programming, and when is it useful?",
        "model_answer": "Dynamic programming solves a problem by breaking it into overlapping subproblems, solving each one only once, and storing (memoizing) its result to avoid recomputing it -- it's useful for optimization problems with overlapping subproblems and optimal substructure, like Fibonacci numbers or the knapsack problem.",
        "min_clusters_required": 2,
        "keyword_clusters": [
            {"name": "Overlapping Subproblems", "aliases": ["overlapping subproblem", "subproblems", "breaking into subproblems", "smaller subproblems"]},
            {"name": "Memoization / Caching Results", "aliases": ["memoiz", "cache", "storing results", "store the result", "storing previous results"]},
            {"name": "Optimal Substructure", "aliases": ["optimal substructure", "reuse solutions", "avoid recomputation", "avoid recomputing"]},
        ],
    },
    {
        "id": "dsa-sa-5",
        "courseId": "dsa",
        "mode": "short_answer",
        "tier": 1,
        "prompt": "What is the difference between an Array and a Linked List?",
        "model_answer": "An array stores elements in contiguous memory with fixed size and O(1) index access, but inserting or removing in the middle is expensive because elements have to shift. A linked list stores elements as nodes scattered in memory, each pointing to the next, so inserting/removing is fast but there's no O(1) random access -- you have to walk the list.",
        "min_clusters_required": 2,
        "keyword_clusters": [
            {"name": "Contiguous Memory", "aliases": ["contiguous", "fixed size", "continuous memory", "next to each other in memory"]},
            {"name": "Nodes and Pointers", "aliases": ["node", "pointer", "points to the next", "next reference"]},
            {"name": "Access vs Insert Tradeoff", "aliases": ["random access", "o(1) access", "insertion is faster", "shifting elements"]},
        ],
    },
    {
        "id": "dsa-sa-6",
        "courseId": "dsa",
        "mode": "short_answer",
        "tier": 3,
        "prompt": "Explain the trade-off between Time Complexity and Space Complexity, using an example.",
        "model_answer": "Time complexity measures how an algorithm's runtime grows with input size, while space complexity measures how its memory usage grows -- and often you can trade one for the other, like using extra memory (a hash map or memoization table) to cache results and cut runtime, or using less memory at the cost of recomputing values.",
        "min_clusters_required": 2,
        "keyword_clusters": [
            {"name": "Time = Runtime Growth", "aliases": ["runtime grows", "how long it takes", "execution time", "speed of the algorithm"]},
            {"name": "Space = Memory Growth", "aliases": ["memory usage", "memory grows", "extra memory", "space used"]},
            {"name": "Trading One for the Other", "aliases": ["trade off", "tradeoff", "use more memory to save time", "cache to save time"]},
        ],
    },
]